import numpy as np
import openai
from api.response import ChatGptResponse


def get_description(arousal: list, valence: list) -> ChatGptResponse:
    """
    Generates a description of a song based on its arousal and valence values using OpenAI GPT-3 model.

    Args:
        arousal (list): Array of arousal values of the song
        valence (list): Array of valence values of the song

    Returns:
        str: A description of the song based on its arousal and valence values generated by the GPT-3 model.
    """
    openai.api_key = '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'

    arousal_mean = np.mean(arousal)
    valence_mean = np.mean(valence)
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user",
             "content": f"Задача: опиши мне эмоцию песни, у которой arousal = {arousal_mean}, valence = {valence_mean}"}])
    response = ChatGptResponse(text=completion.choices[0].message.content)

    return response
