import numpy as np
import openai
from api.response import ChatGptResponse


def get_description(arousal: float, valence: float) -> ChatGptResponse:
    """
    Generates a description of a song based on its arousal and valence values using OpenAI GPT-3 model.

    Args:
        arousal (float): Array of arousal values of the song
        valence (float): Array of valence values of the song

    Returns:
        str: A description of the song based on its arousal and valence values generated by the GPT-3 model.
    """
    openai.api_key = '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'

    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user",
             "content": f"Задача: опиши мне эмоцию песни, у которой arousal = {arousal}, valence = {valence}"}])
    response = ChatGptResponse(text=completion.choices[0].message.content)

    return response
