version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
#  frontend:
#    build:
#      context: demo
#      dockerfile: demo/Dockerfile
#    ports:
#      - "8080:8080"
