import os
import openai
import numpy as np


def get_description(arousal: list, valence: list, openai_key: str):
    """
    Generates a description of a song based on its arousal and valence values using OpenAI GPT-3 model.

    Args:
        arousal (list): Array of arousal values of the song
        valence (list): Array of valence values of the song

    Returns:
        str: A description of the song based on its arousal and valence values generated by the GPT-3 model.
    """
    openai.api_key = openai_key
    
    arousal_mean = np.mean(arousal)
    valence_mean = np.mean(valence)
    print(arousal_mean)
    print(valence_mean)
    completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", 
         "content": f"Задача: опиши мне эмоцию песни, у которой arousal = {arousal_mean}, valence = {valence_mean}"}])
    print(completion.choices[0].message.content)
    return completion.choices[0].message.content